#!/bin/bash -v

ln -s ~/.dotfiles/.inputrc ~/.inputrc
ln -s ~/.dotfiles/.bash_aliases ~/.bash_aliases
ln -s ~/.dotfiles/.bashrc ~/.profile
ln -s ~/.dotfiles/.vim ~/.vim
ln -s ~/.dotfiles/.vimrc ~/.vimrc
ln -s ~/.dotfiles/.jrnl_config ~/.jrnl_config
