#!/bin/bash -v

ln -s ~/.dotfiles/bash_aliases ~/.bash_aliases
ln -s ~/.dotfiles/vimrc ~/.vimrc

if [ ! -L ~/.vim ]; then
	ln -s ~/.dotfiles/.vim ~/.vim
fi

if [ -a /etc/redhat-release ]; then
	ln -s ~/.dotfiles/i3 ~/.config/i3
	ln -s ~/.dotfiles/tmux.conf ~/.tmux.conf
fi
